# Generated by Django 4.1.1 on 2022-09-25 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='image',
            field=models.ImageField(upload_to='servicios'),
        ),
    ]
