# Generated by Django 4.1.1 on 2022-09-25 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_alter_servicio_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='image',
            new_name='imagen',
        ),
    ]
