# Generated by Django 4.1.1 on 2022-09-26 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0006_alter_servicio_contenido_alter_servicio_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ['nombre'], 'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterModelOptions(
            name='servicio',
            options={'ordering': ['titulo'], 'verbose_name': 'servicio', 'verbose_name_plural': 'servicios'},
        ),
    ]
