# Generated by Django 4.1.1 on 2022-09-26 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0007_alter_empresa_options_alter_servicio_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='distrito',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
