# Generated by Django 4.1.1 on 2022-09-26 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0008_empresa_distrito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='distrito',
        ),
    ]
