# Generated by Django 4.1.1 on 2022-09-26 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_categoria_id_alter_post_contenido_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nombre'], 'verbose_name': 'categoria', 'verbose_name_plural': 'categorias'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['titulo'], 'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
    ]
